spring:
  version: 3.0.2
  application:
    name: test-mca
    version: 0.0.1
#  datasource:
#    url: jdbc:postgresql://localhost:5432/some-postgres
#    username: sa
#    password: password
  datasource:
    url: jdbc:h2:mem:testdbmca
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true